module Renv
  class EnvTypes
    def initialize(env_file = '.env')
      @env = EnvFile.new(env_file).vars
    end

    desc 'generate OUTPUT_PATH', 'Generates Typescript definitions from the .env file'
    def generate(output_path)
      ts = <<~TS
        // Generated by renv — do not edit manually
        declare namespace NodeJS {
          interface ProcessEnv {
      TS

      @env.each do |key, _|
        ts += " #{key}: string;\n"
      end

      ts += <<~TS
          }
        }
      TS

      dirname = File.dirname(output_path)
      Dir.mkdir(dirname) unless Dir.exist?(dirname)
      File.write(output_path, ts)
    end
  end
end
