module Renv
  module Generators 
    class PythonGenerator < BaseGenerator
      PY_TYPES = {
        string: "str",
        integer: "int",
        boolean: "bool"
      }

      def generate(path)
        content = "// Generated by renv — do not edit manually \n"
        content << "from dataclasses import dataclass\n\n"
        content << "@dataclass\n"
        content << "class Config:\n"

        keys.each do |key|
          py_name = key.lowercase rescue key.downcase
          py_type = PY_TYPES[type_of(key)] || :str

          content << "  #{py_name}: #{py_type}\n"
        end

        File.write(path, content)
      end
    end
  end
end
