require_relative '../test_helper'

class TestGoGenerator < Test::Unit::TestCase 

  def setup
    # Important to have all data types here to check compatibility
    @test_schema = {
      api_key: :string,
      port: 123,
      debug_mode: true,
      unmapped_key: :unknown
    }
    @generator = Renv::Generators::GoGenerator.new(@test_schema)
    @output_dir = 'tmp/test'
    @output_path = File.join(@output_dir, 'config.go')
    FileUtils.mkdir_p(@output_dir)
  end

  def teardown
    File.delete(@output_path) if File.exist?(@output_path)
    FileUtils.rm_r(@output_dir) if File.directory?(@output_dir)
  end

  # Test 1: Check generated go struct content
  def test_generated_go_content
    @generator.generate(@output_path)

    generated_content = File.read(@output_path)

    expected_content = <<~GO
      // Generated by renv — do not edit manually 
      package env

      type Config struct {
        Api_key string `env:"api_key"`
        Port int `env:"port"`
        Debug_mode bool `env:"debug_mode"`
        Unmapped_key string `env:"unmapped_key"`
      }
    GO

    assert_equal expected_content, generated_content,
                 'The generated Go struct content does not match the expectation.'
  end

  # Test 2: Check that the file was actually written
  def test_file_writing
    refute File.exist?(@output_path), 'Pre-condition fail: Output file should not exist before test.'

    @generator.generate(@output_path)

    assert File.exist?(@output_path), 'File.write was not called or failed to create the output file.'
  end

  # Test 3: Check correct capitalization and type mapping (detailed content validation)
  def test_key_to_go_conversion
    @generator.generate(@output_path)
    content = File.read(@output_path)

    assert_match(/Api_key string `env:"api_key"`/, content, 'API Key mapping failed.')
    assert_match(/Port int `env:"port"`/, content, 'Port mapping failed.')
    assert_match(/Debug_mode bool `env:"debug_mode"`/, content, 'DebugMode mapping failed.')

    assert_match(/Unmapped_key string `env:"unmapped_key"`/, content, 'Inherited default type mapping failed.')
  end
end
